### ISSUE TITLE
Creation of tag 1.2.2

### ISSUE THREAD

**Issue by Luk1298** [MAXakaWIZARD/PoParser#4]
Hello Max,

with this issue I would like to ask you to create a new tag called "1.2.2" before the "1.3.0" tag.
Could you create this tag, please?

You can use: "git tag 1.2.2 f229850f73edc681f71f5527bf10945f7bf2f994"
This commit is the last before 2020 (2016).

Currently I am using PHP 5.* and I am not able to upgrade PHP as fast as possible. Thats the reason why I have to use a 1.2.* version. There are some commits between 1.2.1 and 1.3.0 that I need but can not use in case of the missing tag.

I am looking forward to hearing from you. Thank you for your help and time.

Kind regards
Lukas Rühl

**Comment by MAXakaWIZARD** [comment]
@Luk1298 v1.2.2 has been created: https://github.com/MAXakaWIZARD/PoParser/releases/tag/1.2.2

**Comment by Luk1298** [comment]
Thank you so much for creating this new tag. Have a nice day.

**Comment by MAXakaWIZARD** [comment]
@Luk1298 you're welcome. Have a nice day too!
